### PR TITLE
New NativeDiscovery constructor with optional explicit path parameters

### PR DESCRIPTION
**Pull request by laim0nas100**
Old functionality has been preserved
Tested on Windows and Linux
The old way to add custom path (NativeLibrary.addSearchPath) doesn't work on Windows 
IMO more user-friendly API

### CODE REVIEW

**Comment by caprica** [comment]
Your commit changes every single line in the file, this can not be right.

The API might be more friendly in your opinion, but from my point of view it is the responsibility of the discovery strategy implementations to deal with OS-specific path handling, not this component itself. If you want to change path handling, provide your own strategy implementation and use that. If you don't like the API, wrap it in your own component.

You say NativeLibrary.addSearchPath (a JNA function) does not work on Windows, yet that code is still present in your patch. Last I tested, addSearchPath worked just fine on Windows so please elaborate.

**Comment by laim0nas100** [comment]
Hello, thank you for your response.
I should've specified what doesn't work on windows.
After making a NativeLibrary.addSearchPath call, it does find the library, but it fails if you have no VLC_PLUGIN_PATH env. variable. My VLC plugins are where they are in any standard installation ([vlcpath]\plugins) and just calling NativeLibrary.addSearchPath is not enough. If you follow up that call with LibC.INSTANCE._putenv with correct plugin path (like it's done in DefaultWindowsNativeDiscoveryStrategy) then it works.

I've used API wrapper as you've mentioned for path handling, but i though this could be a useful addition.
I understand If this is against your design intentions.

**Comment by caprica** [comment]
I'm trying to understand if there's something I should try and improve here... we still need NativeLibrary.addSearchPath and LibC.INSTANCE._putenv, and this is already in DefaultWindowsNativeDiscoveryStrategy, so where is actually going wrong?

Adding specific paths via a new constructor seems to be for an unrelated reason?

**Comment by laim0nas100** [comment]
Everything is fine, if DefaultWindowsNativeDiscoveryStrategy manages to locate VLC path, otherwise configuring custom path needs a bit of fiddling, which this implementations hides.

**Comment by caprica** [comment]
So then the idea is that you add your own paths to your own instance of a DefaultWindowsNativeDiscoveryStrategy similar to what you do here in an anonymous sub-class and pass that implementation in the NativeDiscovery constructor.

The key idea here is that all that stuff gets pushed to the particular strategy implementation, and you don't "pollute" the common NativeDiscovery component.

You'd end up doing something like this:

new NativeDiscovery(
    new DefaultLinuxNativeDiscoveryStrategy(),
    new MyExtendedWindowsNativeDiscoveryStrategy(path1, path2, path3),
    new DefaultMacNativeDiscoveryStrategy()
).discover();

You can have MyExtendedWindowsNativeDiscoveryStrategy extend DefaultWindowsNativeDiscoveryStrategy, or do your own thing entirely, specifying paths however you want.

**Comment by laim0nas100** [comment]
I see that this issue is more of a design intent. I know how to go about implementing custom paths with a wrapper, but this might not be obvious for a common user that has not looked at how it actually finds and initializes the library (sets the plugin env. path), which I try to simplify in my implementation. Pushing path-setting to a extended DiscoveryStradegy class is the way i was doing this before, and i understand if you want to keep it that way.

**Comment by laim0nas100** [comment]
I just realized it doesn't completely cover all previous functionality which was one of my goals (can't pass an array of NativeDiscoveyStrategy). Anyway, thanks for taking your time to look at my suggestion.

**Pull request closed without merging**
