### PR TITLE
Ease discovering in additional directories

### LINKED ISSUE #646: Adding a folder to NativeDiscovery on every platform
I have a cross-platform application where I want to be able to call the Discovery with a specific directory and then have it do its default Discovery plus look into that directory.

As I see it right now, I have to extend all three NativeDiscoveryStrategies and add the folder in `onGetDirectoryNames`, which is super annoying. What if the constructor of every DefaultDiscoveryStrategy had a varargs parameter that would take additional directories? Is super easy to implement and would this usecase a lot easier.

### PR DESCRIPTION
**Pull request by Xerus2000**
Fixes #646

### CODE REVIEW

**Comment by caprica** [comment]
I'm still not convinced this is necessary for the core library. In any case, those commits should be squashed IMO.

**Comment by Xerus2000** [comment]
I always squash merge, so that's not an issue. 
Do you have a substantial argument against the proposal? IMO it doesn't hurt having this feature, and it can be very useful at times.

**Comment by stefan-reich** [comment]
Yes, why not commit this?

**Comment by caprica** [comment]
The truth of the matter is in hindsight I wish I'd never added any of this native discovery stuff to vlcj, since it's really about JNA not vlcj.

Why should a mini-framework be created around a single Native.loadLibrary(...) call that most applications won't even need if their environment is set up correctly?

So I am still considering what to do.

**Comment by caprica** [comment]
Why JNA?

Because all that vlcj's NativeDiscovery implementation is, is a mini-framework around this:

```
com.sun.jna.NativeLibrary.addSearchPath("libvlc", "some path");
com.sun.jna.Native.loadLibrary("libvlc");
```

You can use vlcj successfully without using vlcj's NativeDiscovery class, the native discovery in vlcj was added as a convenience for lazy developers or those that can't set their environment up correctly.

There is IMO a stronger argument for saying JNA itself should do a better job of finding native libraries, so put this kind of code in JNA instead of vlcj.

So while it may seem on the surface like I'm splitting hairs on this issue, it's actually deeper than it may first appear.

What do I mean about setting up the environment correctly? Read the JNA documentation here:

https://github.com/java-native-access/jna/blob/master/www/GettingStarted.md

As you can see, loading the native library is nothing at all to do with vlcj.

**Comment by caprica** [comment]
I did finally find time to address this, indirectly at least, as part of the vlcj-4 refactoring under #697.

The solution is explained in #697 and the commit log referenced by that ticket.

**Pull request closed without merging**
